---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dep
  labels:
    env: pre-prod
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-con
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD 
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
  replicas: 3
  selector:
    matchLabels:
      app: postgres-app
