---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-dep
  labels:
    env: pre-prod
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-con
          image:
  replicas: 3
  selector:
    matchLabels:
      app: worker-app
