---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    env: pre-prod
    code: wiwue
spec:
  template:
    metadata:
      name: my-rc-pod
      labels:
        env: pre-prod
        code: kxjd
    spec:
      containers:
        - name: my-rc-con
          image: httpd:2.4-alpine
  replicas: 3
